// Generated by gencpp from file xf_mic_asr_offline/Set_Led_On_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_SET_LED_ON_SRV_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_SET_LED_ON_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/Set_Led_On_srvRequest.h>
#include <xf_mic_asr_offline/Set_Led_On_srvResponse.h>


namespace xf_mic_asr_offline
{

struct Set_Led_On_srv
{

typedef Set_Led_On_srvRequest Request;
typedef Set_Led_On_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set_Led_On_srv
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srv > {
  static const char* value()
  {
    return "8714bec2ad75b727b5f6fac35cbcb6ff";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::Set_Led_On_srv > {
  static const char* value()
  {
    return "xf_mic_asr_offline/Set_Led_On_srv";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srvRequest> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Set_Led_On_srvRequest> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Set_Led_On_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Set_Led_On_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Set_Led_On_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srvResponse> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Set_Led_On_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Set_Led_On_srvResponse> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Set_Led_On_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Set_Led_On_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Set_Led_On_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Led_On_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_SET_LED_ON_SRV_H
