// Generated by gencpp from file xf_mic_asr_offline/Set_Awake_Word_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_SET_AWAKE_WORD_SRV_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_SET_AWAKE_WORD_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/Set_Awake_Word_srvRequest.h>
#include <xf_mic_asr_offline/Set_Awake_Word_srvResponse.h>


namespace xf_mic_asr_offline
{

struct Set_Awake_Word_srv
{

typedef Set_Awake_Word_srvRequest Request;
typedef Set_Awake_Word_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set_Awake_Word_srv
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srv > {
  static const char* value()
  {
    return "7e4b0be2dab296a055fbdac61a8ae954";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::Set_Awake_Word_srv > {
  static const char* value()
  {
    return "xf_mic_asr_offline/Set_Awake_Word_srv";
  }

  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srvRequest> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Set_Awake_Word_srvRequest> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Set_Awake_Word_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Set_Awake_Word_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Set_Awake_Word_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srvResponse> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Set_Awake_Word_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Set_Awake_Word_srvResponse> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Set_Awake_Word_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Set_Awake_Word_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Set_Awake_Word_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Set_Awake_Word_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_SET_AWAKE_WORD_SRV_H
