// Generated by gencpp from file xf_mic_asr_offline/Start_Record_srv.msg
// DO NOT EDIT!


#ifndef XF_MIC_ASR_OFFLINE_MESSAGE_START_RECORD_SRV_H
#define XF_MIC_ASR_OFFLINE_MESSAGE_START_RECORD_SRV_H

#include <ros/service_traits.h>


#include <xf_mic_asr_offline/Start_Record_srvRequest.h>
#include <xf_mic_asr_offline/Start_Record_srvResponse.h>


namespace xf_mic_asr_offline
{

struct Start_Record_srv
{

typedef Start_Record_srvRequest Request;
typedef Start_Record_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start_Record_srv
} // namespace xf_mic_asr_offline


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xf_mic_asr_offline::Start_Record_srv > {
  static const char* value()
  {
    return "f1d612a6ac6a6d5f9f90acdc04ae715a";
  }

  static const char* value(const ::xf_mic_asr_offline::Start_Record_srv&) { return value(); }
};

template<>
struct DataType< ::xf_mic_asr_offline::Start_Record_srv > {
  static const char* value()
  {
    return "xf_mic_asr_offline/Start_Record_srv";
  }

  static const char* value(const ::xf_mic_asr_offline::Start_Record_srv&) { return value(); }
};


// service_traits::MD5Sum< ::xf_mic_asr_offline::Start_Record_srvRequest> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Start_Record_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Start_Record_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Start_Record_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Start_Record_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Start_Record_srvRequest> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Start_Record_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Start_Record_srvRequest>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Start_Record_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Start_Record_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xf_mic_asr_offline::Start_Record_srvResponse> should match 
// service_traits::MD5Sum< ::xf_mic_asr_offline::Start_Record_srv > 
template<>
struct MD5Sum< ::xf_mic_asr_offline::Start_Record_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xf_mic_asr_offline::Start_Record_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Start_Record_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xf_mic_asr_offline::Start_Record_srvResponse> should match 
// service_traits::DataType< ::xf_mic_asr_offline::Start_Record_srv > 
template<>
struct DataType< ::xf_mic_asr_offline::Start_Record_srvResponse>
{
  static const char* value()
  {
    return DataType< ::xf_mic_asr_offline::Start_Record_srv >::value();
  }
  static const char* value(const ::xf_mic_asr_offline::Start_Record_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XF_MIC_ASR_OFFLINE_MESSAGE_START_RECORD_SRV_H
