# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false    # 当move_base在不活动状态时,是否关掉costmap.

controller_frequency: 3.0   # 3.0 向底盘控制移动话题cmd_vel发送命令的频率
controller_patience: 3.0    # 在空间清理操作执行前,控制器花多长时间等有效控制下发.


planner_frequency: 1.0      # 全局规划操作的执行频率.如果设置为0.0,则全局规划器仅
                            # 在接收到新的目标点或者局部规划器报告路径堵塞时才会重新执行规划操作.
planner_patience: 5.0       # 在空间清理操作执行前,留给规划器多长时间来找出一条有效规划.

oscillation_timeout: 20.0    #10.0 执行修复机制前,允许振荡的时长.
oscillation_distance: 0.6   # 来回运动在多大距离以上不会被认为是振荡.

recovery_behavior_enabled: false  # myron

# local planner - default is trajectory rollout
# base_local_planner: "dwa_local_planner/DWAPlannerROS" 
base_local_planner: "teb_local_planner/TebLocalPlannerROS"  # 指定用于move_base的局部规划器插件名称.

base_global_planner: "carrot_planner/CarrotPlanner"                       # 指定用于move_base的全局规划器插件名称.
 #alternatives: global_planner/GlobalPlanner, navfn/NavfnROS


