// Generated by gencpp from file game_start/Play_TTS_srvRequest.msg
// DO NOT EDIT!


#ifndef GAME_START_MESSAGE_PLAY_TTS_SRVREQUEST_H
#define GAME_START_MESSAGE_PLAY_TTS_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace game_start
{
template <class ContainerAllocator>
struct Play_TTS_srvRequest_
{
  typedef Play_TTS_srvRequest_<ContainerAllocator> Type;

  Play_TTS_srvRequest_()
    : text()
    , speakerName()  {
    }
  Play_TTS_srvRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , speakerName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speakerName_type;
  _speakerName_type speakerName;





  typedef boost::shared_ptr< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Play_TTS_srvRequest_

typedef ::game_start::Play_TTS_srvRequest_<std::allocator<void> > Play_TTS_srvRequest;

typedef boost::shared_ptr< ::game_start::Play_TTS_srvRequest > Play_TTS_srvRequestPtr;
typedef boost::shared_ptr< ::game_start::Play_TTS_srvRequest const> Play_TTS_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::game_start::Play_TTS_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace game_start

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a03c769fda3b8bccf2bfe9b616c0c47";
  }

  static const char* value(const ::game_start::Play_TTS_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a03c769fda3b8bcULL;
  static const uint64_t static_value2 = 0xcf2bfe9b616c0c47ULL;
};

template<class ContainerAllocator>
struct DataType< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "game_start/Play_TTS_srvRequest";
  }

  static const char* value(const ::game_start::Play_TTS_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"string speakerName\n"
;
  }

  static const char* value(const ::game_start::Play_TTS_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.speakerName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Play_TTS_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::game_start::Play_TTS_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::game_start::Play_TTS_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "speakerName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speakerName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAME_START_MESSAGE_PLAY_TTS_SRVREQUEST_H
