// Generated by gencpp from file ht_msg/Ht.msg
// DO NOT EDIT!


#ifndef HT_MSG_MESSAGE_HT_H
#define HT_MSG_MESSAGE_HT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ht_msg
{
template <class ContainerAllocator>
struct Ht_
{
  typedef Ht_<ContainerAllocator> Type;

  Ht_()
    : glasses_people(0)
    , longhair_people(0)  {
    }
  Ht_(const ContainerAllocator& _alloc)
    : glasses_people(0)
    , longhair_people(0)  {
  (void)_alloc;
    }



   typedef uint8_t _glasses_people_type;
  _glasses_people_type glasses_people;

   typedef uint8_t _longhair_people_type;
  _longhair_people_type longhair_people;





  typedef boost::shared_ptr< ::ht_msg::Ht_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ht_msg::Ht_<ContainerAllocator> const> ConstPtr;

}; // struct Ht_

typedef ::ht_msg::Ht_<std::allocator<void> > Ht;

typedef boost::shared_ptr< ::ht_msg::Ht > HtPtr;
typedef boost::shared_ptr< ::ht_msg::Ht const> HtConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ht_msg::Ht_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ht_msg::Ht_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ht_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'ht_msg': ['/home/ucar/ROS_xunfei/ucar_ws/src/ht_msg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ht_msg::Ht_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ht_msg::Ht_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ht_msg::Ht_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ht_msg::Ht_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ht_msg::Ht_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ht_msg::Ht_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ht_msg::Ht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79e7595f09184171ab3ff74ad2c7b38d";
  }

  static const char* value(const ::ht_msg::Ht_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79e7595f09184171ULL;
  static const uint64_t static_value2 = 0xab3ff74ad2c7b38dULL;
};

template<class ContainerAllocator>
struct DataType< ::ht_msg::Ht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ht_msg/Ht";
  }

  static const char* value(const ::ht_msg::Ht_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ht_msg::Ht_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 glasses_people\n"
"uint8 longhair_people\n"
;
  }

  static const char* value(const ::ht_msg::Ht_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ht_msg::Ht_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.glasses_people);
      stream.next(m.longhair_people);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ht_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ht_msg::Ht_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ht_msg::Ht_<ContainerAllocator>& v)
  {
    s << indent << "glasses_people: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.glasses_people);
    s << indent << "longhair_people: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.longhair_people);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HT_MSG_MESSAGE_HT_H
