// Generated by gencpp from file robot_localization/FromLL.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_MESSAGE_FROMLL_H
#define ROBOT_LOCALIZATION_MESSAGE_FROMLL_H

#include <ros/service_traits.h>


#include <robot_localization/FromLLRequest.h>
#include <robot_localization/FromLLResponse.h>


namespace robot_localization
{

struct FromLL
{

typedef FromLLRequest Request;
typedef FromLLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FromLL
} // namespace robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization::FromLL > {
  static const char* value()
  {
    return "a6cd7064e35acbe3e4c3ac3dc5fd8265";
  }

  static const char* value(const ::robot_localization::FromLL&) { return value(); }
};

template<>
struct DataType< ::robot_localization::FromLL > {
  static const char* value()
  {
    return "robot_localization/FromLL";
  }

  static const char* value(const ::robot_localization::FromLL&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization::FromLLRequest> should match 
// service_traits::MD5Sum< ::robot_localization::FromLL > 
template<>
struct MD5Sum< ::robot_localization::FromLLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::FromLL >::value();
  }
  static const char* value(const ::robot_localization::FromLLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::FromLLRequest> should match 
// service_traits::DataType< ::robot_localization::FromLL > 
template<>
struct DataType< ::robot_localization::FromLLRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization::FromLL >::value();
  }
  static const char* value(const ::robot_localization::FromLLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization::FromLLResponse> should match 
// service_traits::MD5Sum< ::robot_localization::FromLL > 
template<>
struct MD5Sum< ::robot_localization::FromLLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::FromLL >::value();
  }
  static const char* value(const ::robot_localization::FromLLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::FromLLResponse> should match 
// service_traits::DataType< ::robot_localization::FromLL > 
template<>
struct DataType< ::robot_localization::FromLLResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization::FromLL >::value();
  }
  static const char* value(const ::robot_localization::FromLLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_MESSAGE_FROMLL_H
