// Generated by gencpp from file robot_localization/SetUTMZone.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_MESSAGE_SETUTMZONE_H
#define ROBOT_LOCALIZATION_MESSAGE_SETUTMZONE_H

#include <ros/service_traits.h>


#include <robot_localization/SetUTMZoneRequest.h>
#include <robot_localization/SetUTMZoneResponse.h>


namespace robot_localization
{

struct SetUTMZone
{

typedef SetUTMZoneRequest Request;
typedef SetUTMZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUTMZone
} // namespace robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization::SetUTMZone > {
  static const char* value()
  {
    return "893fd74d45efde020666acda18d3cccc";
  }

  static const char* value(const ::robot_localization::SetUTMZone&) { return value(); }
};

template<>
struct DataType< ::robot_localization::SetUTMZone > {
  static const char* value()
  {
    return "robot_localization/SetUTMZone";
  }

  static const char* value(const ::robot_localization::SetUTMZone&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization::SetUTMZoneRequest> should match 
// service_traits::MD5Sum< ::robot_localization::SetUTMZone > 
template<>
struct MD5Sum< ::robot_localization::SetUTMZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization::SetUTMZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::SetUTMZoneRequest> should match 
// service_traits::DataType< ::robot_localization::SetUTMZone > 
template<>
struct DataType< ::robot_localization::SetUTMZoneRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization::SetUTMZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization::SetUTMZoneResponse> should match 
// service_traits::MD5Sum< ::robot_localization::SetUTMZone > 
template<>
struct MD5Sum< ::robot_localization::SetUTMZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization::SetUTMZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::SetUTMZoneResponse> should match 
// service_traits::DataType< ::robot_localization::SetUTMZone > 
template<>
struct DataType< ::robot_localization::SetUTMZoneResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization::SetUTMZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_MESSAGE_SETUTMZONE_H
