// Generated by gencpp from file robot_localization/ToggleFilterProcessingRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H
#define ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_localization
{
template <class ContainerAllocator>
struct ToggleFilterProcessingRequest_
{
  typedef ToggleFilterProcessingRequest_<ContainerAllocator> Type;

  ToggleFilterProcessingRequest_()
    : on(false)  {
    }
  ToggleFilterProcessingRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleFilterProcessingRequest_

typedef ::robot_localization::ToggleFilterProcessingRequest_<std::allocator<void> > ToggleFilterProcessingRequest;

typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingRequest > ToggleFilterProcessingRequestPtr;
typedef boost::shared_ptr< ::robot_localization::ToggleFilterProcessingRequest const> ToggleFilterProcessingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_localization

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/melodic/share/geographic_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/melodic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_localization/ToggleFilterProcessingRequest";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n"
;
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleFilterProcessingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H
