// Generated by gencpp from file robot_localization/ToggleFilterProcessing.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSING_H
#define ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSING_H

#include <ros/service_traits.h>


#include <robot_localization/ToggleFilterProcessingRequest.h>
#include <robot_localization/ToggleFilterProcessingResponse.h>


namespace robot_localization
{

struct ToggleFilterProcessing
{

typedef ToggleFilterProcessingRequest Request;
typedef ToggleFilterProcessingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleFilterProcessing
} // namespace robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization::ToggleFilterProcessing > {
  static const char* value()
  {
    return "a8e1711976dcda1b8b978eee81e85498";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessing&) { return value(); }
};

template<>
struct DataType< ::robot_localization::ToggleFilterProcessing > {
  static const char* value()
  {
    return "robot_localization/ToggleFilterProcessing";
  }

  static const char* value(const ::robot_localization::ToggleFilterProcessing&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization::ToggleFilterProcessingRequest> should match 
// service_traits::MD5Sum< ::robot_localization::ToggleFilterProcessing > 
template<>
struct MD5Sum< ::robot_localization::ToggleFilterProcessingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization::ToggleFilterProcessingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::ToggleFilterProcessingRequest> should match 
// service_traits::DataType< ::robot_localization::ToggleFilterProcessing > 
template<>
struct DataType< ::robot_localization::ToggleFilterProcessingRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization::ToggleFilterProcessingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization::ToggleFilterProcessingResponse> should match 
// service_traits::MD5Sum< ::robot_localization::ToggleFilterProcessing > 
template<>
struct MD5Sum< ::robot_localization::ToggleFilterProcessingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization::ToggleFilterProcessingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization::ToggleFilterProcessingResponse> should match 
// service_traits::DataType< ::robot_localization::ToggleFilterProcessing > 
template<>
struct DataType< ::robot_localization::ToggleFilterProcessingResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization::ToggleFilterProcessingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSING_H
