// Generated by gencpp from file ucar_controller/GetBatteryInfoRequest.msg
// DO NOT EDIT!


#ifndef UCAR_CONTROLLER_MESSAGE_GETBATTERYINFOREQUEST_H
#define UCAR_CONTROLLER_MESSAGE_GETBATTERYINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ucar_controller
{
template <class ContainerAllocator>
struct GetBatteryInfoRequest_
{
  typedef GetBatteryInfoRequest_<ContainerAllocator> Type;

  GetBatteryInfoRequest_()
    {
    }
  GetBatteryInfoRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBatteryInfoRequest_

typedef ::ucar_controller::GetBatteryInfoRequest_<std::allocator<void> > GetBatteryInfoRequest;

typedef boost::shared_ptr< ::ucar_controller::GetBatteryInfoRequest > GetBatteryInfoRequestPtr;
typedef boost::shared_ptr< ::ucar_controller::GetBatteryInfoRequest const> GetBatteryInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ucar_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucar_controller/GetBatteryInfoRequest";
  }

  static const char* value(const ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBatteryInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ucar_controller::GetBatteryInfoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UCAR_CONTROLLER_MESSAGE_GETBATTERYINFOREQUEST_H
