// Generated by gencpp from file ucar_controller/GetBatteryInfo.msg
// DO NOT EDIT!


#ifndef UCAR_CONTROLLER_MESSAGE_GETBATTERYINFO_H
#define UCAR_CONTROLLER_MESSAGE_GETBATTERYINFO_H

#include <ros/service_traits.h>


#include <ucar_controller/GetBatteryInfoRequest.h>
#include <ucar_controller/GetBatteryInfoResponse.h>


namespace ucar_controller
{

struct GetBatteryInfo
{

typedef GetBatteryInfoRequest Request;
typedef GetBatteryInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBatteryInfo
} // namespace ucar_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_controller::GetBatteryInfo > {
  static const char* value()
  {
    return "0f586d9a0cd4ac8575cd2b82e8d112d3";
  }

  static const char* value(const ::ucar_controller::GetBatteryInfo&) { return value(); }
};

template<>
struct DataType< ::ucar_controller::GetBatteryInfo > {
  static const char* value()
  {
    return "ucar_controller/GetBatteryInfo";
  }

  static const char* value(const ::ucar_controller::GetBatteryInfo&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_controller::GetBatteryInfoRequest> should match 
// service_traits::MD5Sum< ::ucar_controller::GetBatteryInfo > 
template<>
struct MD5Sum< ::ucar_controller::GetBatteryInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_controller::GetBatteryInfo >::value();
  }
  static const char* value(const ::ucar_controller::GetBatteryInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_controller::GetBatteryInfoRequest> should match 
// service_traits::DataType< ::ucar_controller::GetBatteryInfo > 
template<>
struct DataType< ::ucar_controller::GetBatteryInfoRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_controller::GetBatteryInfo >::value();
  }
  static const char* value(const ::ucar_controller::GetBatteryInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_controller::GetBatteryInfoResponse> should match 
// service_traits::MD5Sum< ::ucar_controller::GetBatteryInfo > 
template<>
struct MD5Sum< ::ucar_controller::GetBatteryInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_controller::GetBatteryInfo >::value();
  }
  static const char* value(const ::ucar_controller::GetBatteryInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_controller::GetBatteryInfoResponse> should match 
// service_traits::DataType< ::ucar_controller::GetBatteryInfo > 
template<>
struct DataType< ::ucar_controller::GetBatteryInfoResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_controller::GetBatteryInfo >::value();
  }
  static const char* value(const ::ucar_controller::GetBatteryInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_CONTROLLER_MESSAGE_GETBATTERYINFO_H
