// Generated by gencpp from file ucar_controller/SetMaxVel.msg
// DO NOT EDIT!


#ifndef UCAR_CONTROLLER_MESSAGE_SETMAXVEL_H
#define UCAR_CONTROLLER_MESSAGE_SETMAXVEL_H

#include <ros/service_traits.h>


#include <ucar_controller/SetMaxVelRequest.h>
#include <ucar_controller/SetMaxVelResponse.h>


namespace ucar_controller
{

struct SetMaxVel
{

typedef SetMaxVelRequest Request;
typedef SetMaxVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMaxVel
} // namespace ucar_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_controller::SetMaxVel > {
  static const char* value()
  {
    return "62b58549939b0f5c8c78eafc0badef0e";
  }

  static const char* value(const ::ucar_controller::SetMaxVel&) { return value(); }
};

template<>
struct DataType< ::ucar_controller::SetMaxVel > {
  static const char* value()
  {
    return "ucar_controller/SetMaxVel";
  }

  static const char* value(const ::ucar_controller::SetMaxVel&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_controller::SetMaxVelRequest> should match 
// service_traits::MD5Sum< ::ucar_controller::SetMaxVel > 
template<>
struct MD5Sum< ::ucar_controller::SetMaxVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_controller::SetMaxVel >::value();
  }
  static const char* value(const ::ucar_controller::SetMaxVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_controller::SetMaxVelRequest> should match 
// service_traits::DataType< ::ucar_controller::SetMaxVel > 
template<>
struct DataType< ::ucar_controller::SetMaxVelRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_controller::SetMaxVel >::value();
  }
  static const char* value(const ::ucar_controller::SetMaxVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_controller::SetMaxVelResponse> should match 
// service_traits::MD5Sum< ::ucar_controller::SetMaxVel > 
template<>
struct MD5Sum< ::ucar_controller::SetMaxVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_controller::SetMaxVel >::value();
  }
  static const char* value(const ::ucar_controller::SetMaxVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_controller::SetMaxVelResponse> should match 
// service_traits::DataType< ::ucar_controller::SetMaxVel > 
template<>
struct DataType< ::ucar_controller::SetMaxVelResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_controller::SetMaxVel >::value();
  }
  static const char* value(const ::ucar_controller::SetMaxVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_CONTROLLER_MESSAGE_SETMAXVEL_H
